# Generated by Django 4.2.3 on 2023-08-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='creatrd_at',
            new_name='created_at',
        ),
    ]
