# Generated by Django 4.2.3 on 2023-08-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0002_rename_creatrd_at_advertisement_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
